/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    'product-categories': ProductCategory;
    pages: Page;
    settings: Setting;
    messages: Message;
    posts: Post;
    projects: Project;
    gallery: Gallery;
    team: Team;
    'home-sections': HomeSection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'home-sections': HomeSectionsSelect<false> | HomeSectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * مدیریت کاتالوگ محصولات صنعتی، دیزل ژنراتورها، پمپ‌ها و تجهیزات
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * مثلاً: centrifugal-pump-500
   */
  slug: string;
  /**
   * دسته‌بندی اصلی محصول را انتخاب کنید.
   */
  category?: (string | null) | ProductCategory;
  featuredImage?: (string | null) | Media;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * حداکثر ۱۶۰ کاراکتر. در صفحه اصلی و نتایج جستجو نمایش داده می‌شود.
   */
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specifications?:
    | {
        standardFeature?:
          | (
              | 'flowRate'
              | 'head'
              | 'power'
              | 'kva'
              | 'engineModel'
              | 'coolingType'
              | 'suctionDepth'
              | 'solidsHandling'
              | 'tableSize'
              | 'speed'
              | 'standard'
              | 'impellerMaterial'
              | 'casingMaterial'
              | 'shaftMaterial'
              | 'sealType'
              | 'maxTemp'
              | 'maxPressure'
              | 'flangeRating'
              | 'weight'
              | 'custom'
            )
          | null;
        customLabel?: string | null;
        label?: string | null;
        value: string;
        unit?: string | null;
        isNumeric?: boolean | null;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        title: string;
        file: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * اگه خالی باشه، نام محصول استفاده میشه. حداکثر ۶۰ کاراکتر.
   */
  metaTitle?: string | null;
  /**
   * اگه خالی باشه، توضیح کوتاه استفاده میشه. حداکثر ۱۶۰ کاراکتر.
   */
  metaDescription?: string | null;
  /**
   * مثلاً: پمپ سانتریفیوژ, پمپ فشار قوی, پمپ نفت و گاز, هزاره کالا
   */
  keywords?: string | null;
  /**
   * اگه این محصول از یه صفحه دیگه کپی شده، آدرس صفحه اصلی رو بذارید.
   */
  canonicalUrl?: string | null;
  isFeatured?: boolean | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * دسته‌بندی‌های محصولات از این بخش مدیریت می‌شوند.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: string;
  title: string;
  /**
   * فقط انگلیسی و بدون فاصله. مثال: centrifugal
   */
  slug: string;
  /**
   * اختیاری. برای توضیح داخلی یا استفاده‌های بعدی در سایت.
   */
  description?: string | null;
  /**
   * اختیاری. برای توسعه‌های بعدی سایت.
   */
  image?: (string | null) | Media;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * اسلاگ صفحه (مانند home, compare, about, products, projects, gallery, capabilities, contact, blog)
   */
  slug: string;
  subtitle?: string | null;
  heroImage?: (string | null) | Media;
  /**
   * در صورت آپلود، اسلایدها نادیده گرفته می‌شوند و این ویدیو در پس‌زمینه پخش می‌شود. فرمت MP4، بدون صدا، ۱۰-۱۵ ثانیه.
   */
  heroVideo?: (string | null) | Media;
  /**
   * متن‌ها، تیتر سه سطری و دکمه‌های نمایش داده شده روی ویدیو
   */
  heroVideoContent?: {
    badge?: string | null;
    titleLine1?: string | null;
    titleHighlight?: string | null;
    titleLine3?: string | null;
    description?: string | null;
    primaryCtaText?: string | null;
    primaryCtaLink?: string | null;
    secondaryCtaText?: string | null;
    secondaryCtaLink?: string | null;
  };
  /**
   * فقط برای صفحه home کاربرد دارد
   */
  heroSlides?:
    | {
        image: string | Media;
        video?: (string | null) | Media;
        title?: string | null;
        badge?: string | null;
        titleLine1?: string | null;
        titleHighlight?: string | null;
        titleLine3?: string | null;
        description?: string | null;
        primaryCtaText?: string | null;
        primaryCtaLink?: string | null;
        secondaryCtaText?: string | null;
        secondaryCtaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isPublished?: boolean | null;
  /**
   * حداکثر ۶۰ کاراکتر. اگر خالی باشد، عنوان صفحه استفاده می‌شود.
   */
  metaTitle?: string | null;
  /**
   * حداکثر ۱۶۰ کاراکتر. اگر خالی باشد، excerpt استفاده می‌شود.
   */
  metaDescription?: string | null;
  /**
   * در metabox جستجو و کارت‌های اشتراک‌گذاری نمایش داده می‌شود.
   */
  excerpt?: string | null;
  introSection?: {
    badge?: string | null;
    title?: string | null;
    story?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  credentials?: {
    boxTitle?: string | null;
    companyType?: string | null;
    registeredName?: string | null;
    registrationNumber?: string | null;
    nationalId?: string | null;
    economicCode?: string | null;
    ceo?: string | null;
    location?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
  };
  stats?:
    | {
        number: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  strategicGoals?:
    | {
        title: string;
        description: string;
        icon?: ('vision' | 'mission' | 'values' | 'quality') | null;
        id?: string | null;
      }[]
    | null;
  workstations?:
    | {
        title: string;
        description: string;
        equipment?: string | null;
        capacity?: string | null;
        image?: (string | null) | Media;
        icon?: ('machining' | 'testing' | 'balancing' | 'qc' | 'assembly' | 'engineering' | 'facility') | null;
        id?: string | null;
      }[]
    | null;
  companyGrounds?:
    | {
        title?: string | null;
        image: string | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  capabilitiesIntro?: {
    badge?: string | null;
    title?: string | null;
  };
  plantHighlight?: {
    hydrostaticStandard?: string | null;
    rollingCapacity?: string | null;
    maxCraneCapacity?: string | null;
    powerGenerator?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  siteName?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  aboutText?: string | null;
  logo?: (string | null) | Media;
  logoDark?: (string | null) | Media;
  headerNavItems?:
    | {
        label: string;
        href: string;
        isExternal?: boolean | null;
        id?: string | null;
      }[]
    | null;
  headerCtaText?: string | null;
  headerCtaLink?: string | null;
  footerQuickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerProductLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  certificates?:
    | {
        image: string | Media;
        title?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  fullName: string;
  company?: string | null;
  phone: string;
  email?: string | null;
  subject: string;
  message: string;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (string | null) | Media;
  author?: string | null;
  category?: ('centrifugal' | 'piston' | 'gear' | 'maintenance' | 'news' | 'technical') | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  isPublished?: boolean | null;
  publishedAt?: string | null;
  /**
   * حداکثر ۶۰ کاراکتر. اگر خالی باشد، عنوان مقاله استفاده می‌شود.
   */
  metaTitle?: string | null;
  /**
   * حداکثر ۱۶۰ کاراکتر. اگر خالی باشد، excerpt استفاده می‌شود.
   */
  metaDescription?: string | null;
  keywords?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  slug: string;
  client?: string | null;
  location?: string | null;
  /**
   * مثلاً: ۱۴۰۲/۰۶/۱۵
   */
  completionDate?: string | null;
  description?: string | null;
  featuredImage?: (string | null) | Media;
  isFeatured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  title?: string | null;
  image: string | Media;
  category?: ('workshop' | 'products' | 'projects' | 'team' | 'other') | null;
  isFeatured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  name: string;
  position: string;
  photo?: (string | null) | Media;
  bio?: string | null;
  linkedin?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-sections".
 */
export interface HomeSection {
  id: string;
  /**
   * مثلاً: انتخابی هوشمندانه برای صنعت شما
   */
  title: string;
  subtitle?: string | null;
  sectionKey: 'why-us' | 'capabilities' | 'process';
  theme: 'dark' | 'light';
  /**
   * برای بخش‌هایی که نیاز به تصویر پس‌زمینه دارند
   */
  backgroundImage?: (string | null) | Media;
  isActive?: boolean | null;
  order?: number | null;
  whyUsCards?:
    | {
        title: string;
        description: string;
        icon?: ('engineering' | 'quality' | 'speed' | 'support') | null;
        id?: string | null;
      }[]
    | null;
  capabilityItems?:
    | {
        title: string;
        description: string;
        icon?: ('design' | 'manufacturing' | 'testing' | 'quality-ctrl' | 'installation' | 'service') | null;
        size?: ('normal' | 'large' | 'tall') | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        title: string;
        description: string;
        stepNumber: number;
        icon?: ('analysis' | 'design' | 'build' | 'test' | 'deliver') | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: string | ProductCategory;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'settings';
        value: string | Setting;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'home-sections';
        value: string | HomeSection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  fullDescription?: T;
  specifications?:
    | T
    | {
        standardFeature?: T;
        customLabel?: T;
        label?: T;
        value?: T;
        unit?: T;
        isNumeric?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        title?: T;
        file?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  canonicalUrl?: T;
  isFeatured?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  heroImage?: T;
  heroVideo?: T;
  heroVideoContent?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleHighlight?: T;
        titleLine3?: T;
        description?: T;
        primaryCtaText?: T;
        primaryCtaLink?: T;
        secondaryCtaText?: T;
        secondaryCtaLink?: T;
      };
  heroSlides?:
    | T
    | {
        image?: T;
        video?: T;
        title?: T;
        badge?: T;
        titleLine1?: T;
        titleHighlight?: T;
        titleLine3?: T;
        description?: T;
        primaryCtaText?: T;
        primaryCtaLink?: T;
        secondaryCtaText?: T;
        secondaryCtaLink?: T;
        id?: T;
      };
  content?: T;
  isPublished?: T;
  metaTitle?: T;
  metaDescription?: T;
  excerpt?: T;
  introSection?:
    | T
    | {
        badge?: T;
        title?: T;
        story?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  credentials?:
    | T
    | {
        boxTitle?: T;
        companyType?: T;
        registeredName?: T;
        registrationNumber?: T;
        nationalId?: T;
        economicCode?: T;
        ceo?: T;
        location?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  strategicGoals?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  workstations?:
    | T
    | {
        title?: T;
        description?: T;
        equipment?: T;
        capacity?: T;
        image?: T;
        icon?: T;
        id?: T;
      };
  companyGrounds?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        id?: T;
      };
  capabilitiesIntro?:
    | T
    | {
        badge?: T;
        title?: T;
      };
  plantHighlight?:
    | T
    | {
        hydrostaticStandard?: T;
        rollingCapacity?: T;
        maxCraneCapacity?: T;
        powerGenerator?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  phone?: T;
  email?: T;
  address?: T;
  aboutText?: T;
  logo?: T;
  logoDark?: T;
  headerNavItems?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
        id?: T;
      };
  headerCtaText?: T;
  headerCtaLink?: T;
  footerQuickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerProductLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  certificates?:
    | T
    | {
        image?: T;
        title?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  fullName?: T;
  company?: T;
  phone?: T;
  email?: T;
  subject?: T;
  message?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  category?: T;
  content?: T;
  isPublished?: T;
  publishedAt?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  location?: T;
  completionDate?: T;
  description?: T;
  featuredImage?: T;
  isFeatured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  isFeatured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  photo?: T;
  bio?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-sections_select".
 */
export interface HomeSectionsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  sectionKey?: T;
  theme?: T;
  backgroundImage?: T;
  isActive?: T;
  order?: T;
  whyUsCards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  capabilityItems?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        size?: T;
        image?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        stepNumber?: T;
        icon?: T;
        duration?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}




export type Settings = Setting;

export interface CapabilityItem {
  id?: string;
  title: string;
  description: string;
  icon: "design" | "manufacturing" | "testing" | "quality-ctrl" | "installation" | "service";
  size: "normal" | "large" | "tall";
  image?: { url?: string; alt?: string } | string;
}

export interface WhyUsCard {
  id?: string;
  title: string;
  description: string;
  icon: "engineering" | "quality" | "speed" | "support" | "experience" | "innovation";
  counter?: number;
  counterSuffix?: string;
}

export interface ProcessStep {
  id?: string;
  title: string;
  description: string;
  stepNumber: number;
  icon: "analysis" | "design" | "build" | "test" | "deliver";
  duration?: string;
}
